# Generated by Django 4.2.6 on 2024-02-29 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.PositiveSmallIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.PositiveIntegerField()),
                ('docente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.FloatField(max_length=13)),
                ('apellidoPaterno', models.CharField(max_length=35)),
                ('apellidoMaterno', models.CharField(max_length=35)),
                ('nombres', models.CharField(max_length=35)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('vigencia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('IDuser', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=80)),
                ('Ubicacion', models.CharField(max_length=80)),
                ('Contenido', models.CharField(max_length=200)),
                ('Creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='imgpublic')),
                ('Datecompleted', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaMatricula', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictec.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictec.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictec.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Dictamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('IDuser', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=80)),
                ('Oficina', models.CharField(max_length=80)),
                ('Direccion', models.CharField(max_length=80)),
                ('Marca', models.CharField(max_length=80)),
                ('Modelo', models.CharField(max_length=80)),
                ('Num_Serie', models.CharField(max_length=80)),
                ('Caracteristicas', models.CharField(max_length=200)),
                ('Analisis', models.TextField(max_length=1000)),
                ('Dictamen_Final', models.TextField(max_length=1000)),
                ('Creacion', models.DateTimeField(auto_now_add=True)),
                ('Datecompleted', models.DateTimeField(blank=True, null=True)),
                ('Pendiente', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictec.grado'),
        ),
    ]
